### ISSUE TITLE
Allow word of length one to equal zero

### ISSUE THREAD

**Issue by FissoreD** [arnaud-m/cryptator#39]
At this moment the classic solver does not accept words with leading zeroes.
However, it could be interesting to make a cryptarithm of type `-a=a` where `a` must equal zero.

Another case where a single-letter word should be zero is when we force a letter to be zero.
For example in `send+more=money` we are able to add the constraint `m=1` and have  `send+more=money; m=1`.
Similary it would be usefull to be able to declare `o=0` in a similar situation  `send+more=money; o=0`.

**Comment by arnaud-m** [comment]
Note that it becomes trivial to extend a cryptarithm by adding 0 any number of times.

**Comment by arnaud-m** [comment]
- See #59
