### ISSUE TITLE
[FEATURE] Misleading workflow status badge 

### ISSUE THREAD

**Issue by arnaud-m** [arnaud-m/cryptator#54]
**Is your feature request related to a problem? Please describe.**
It seems that the status badge is only triggered by the main branch.
See [here](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge).

**Describe the solution you'd like**
I would prefer that the status badge is triggered by the current branch.

**Provide usage examples**
See commit 058d7aa that has a failing status.

**Comment by Imp95** [comment]
After looking it up it seems that there isn't a native way to set a badge to the "current branch", it can be assigned to a branch if named in the README meaning it will have to be modified for each branch.

Is there a way to collect the name of the current branch in the README.org if yes we could use it as a variable.

**Comment by arnaud-m** [comment]
Have you tried the [event parameter](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge#using-the-event-parameter) ?

**Comment by arnaud-m** [comment]
Postponed. Too complicated.
